apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcs-pylot-dash-ingress
  labels:
    app: dcs-pylot-dash
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dcs-pylot-dash-service
                port:
                  number: {{ .Values.service.port }}
