apiVersion: v1
kind: Service
metadata:
  name: dcs-pylot-dash-service
  labels:
    app: dcs-pylot-dash
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: dcs-pylot-dash
